package com.henrikstabell.nmclc;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLConstructionEvent;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.Logger;

import java.util.Arrays;

/**
 * Created by Hennamann(Ole Henrik Stabell) on 06/03/2018.
 */
public class NMCLCMod extends DummyModContainer {

    public static final String version = "1.0.0";

    public static Logger logger;

    public NMCLCMod() {

        super(new ModMetadata());
        ModMetadata meta = getMetadata();
        meta.modId = "nmclc";
        meta.name = "NMCLC (NoMoreCapsLockCommands)";
        meta.version = version;
        meta.authorList = Arrays.asList("Hennamann");
        meta.description = "Converts commands to lowercase to save time when typing commands while capslock is on.";
        meta.url = "https://github.com/hennamann/NMCLC-Mod";
        meta.autogenerated = false;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

    @Subscribe
    public void modConstruction(FMLConstructionEvent evt){}

    @Subscribe
    public void preInit(FMLPreInitializationEvent evt) {}

    @Subscribe
    public void init(FMLInitializationEvent evt) {}

    @Subscribe
    public void postInit(FMLPostInitializationEvent evt) {}
}